# Application Configuration
spring:
  application:
    name: betting-odds-risk-management
  datasource:
    url: jdbc:h2:mem:bettingdb
    driver-class-name: org.h2.Driver
    username: sa
    password:
    hikari:
      minimum-idle: 5
      maximum-pool-size: 20
      idle-timeout: 30000
      connection-timeout: 30000
      max-lifetime: 1800000
  h2:
    console:
      enabled: true
      path: /h2-console
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.H2Dialect
    defer-datasource-initialization: true
  sql:
    init:
      mode: always
      data-locations: classpath:data.sql

#Prometheus (Actuator + Micrometer)
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  prometheus:
    metrics:
      export:
        enabled: true

server:
  port: 8080
  error:
    include-message: always
    include-binding-errors: always
    include-stacktrace: on_param
    include-exception: false

logging:
  level:
    com.bilyoner.betting: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    enabled: true
    operations-sorter: method
    tags-sorter: alpha

betting:
  odds:
    min-value: 1.00
    reduction-coefficient: 0.15
    increase-coefficient: 0.05
  risk:
    house-edge-margin: 0.05